version: "3.8"
services:
    app:
        image: node:14
        container_name: sample-app
        working_dir: /application
        volumes:
            - .:/application
        links:
            - redis
        ports:
            - "8080:8080"
        command: sh -c "npm install && node app.js"
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"